apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    # Deploy the controller before any application-level Ingress objects.
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    # Upstream Helm chart
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: "1.8.*"
      helm:
        releaseName: aws-load-balancer-controller
        # Layer in values from this repo so the chart stays upstream-clean.
        valueFiles:
          - $values/k8s/ingress/aws-lb-controller/helm-values.yaml
    # Values file lives in the GitOps repo (multi-source Application).
    - repoURL: https://github.com/<your-org>/eks-gitops-microservices-demo
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
