apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rushin85/eks-gitops-microservices-demo.git 
    path: gitops/apps/online-boutique/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true